name: Tests

on:
  push: {}
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev

      - uses: actions/checkout@v3

      - name: run cmake
        working-directory: ${{github.workspace}}/
        run: cmake -B./build .

      - name: make
        working-directory: ${{github.workspace}}/build
        run: make

      - name: Test task 01
        working-directory: ${{github.workspace}}/build
        run: ./task_01/task_01_tests

      - name: Test task 02
        working-directory: ${{github.workspace}}/build
        run: ./task_02/task_02_tests

      - name: Test task 03
        working-directory: ${{github.workspace}}/build
        run: ./task_03/task_03_tests

      - name: Test task 04
        working-directory: ${{github.workspace}}/build
        run: ./task_04/task_04_tests

      - name: Test task 05
        working-directory: ${{github.workspace}}/build
        run: ./task_05/task_05_tests

      - name: Test task 06
        working-directory: ${{github.workspace}}/build
        run: ./task_06/task_06_tests

      - name: Test task 07
        working-directory: ${{github.workspace}}/build
        run: ./task_07/task_07_tests

      - name: Test task 08
        working-directory: ${{github.workspace}}/build
        run: ./task_08/task_08_tests